In [1]:
import numpy as np
a = np.array((1,2,3,4,5,6))
print(a)

[1 2 3 4 5 6]


In [2]:
a.dtype

dtype('int32')

In [3]:
a = np.array([1,2,3,4,5,6], dtype=np.float64)
print(a)

[1. 2. 3. 4. 5. 6.]


In [4]:
a.ndim, a.shape, a.size, a.dtype, a.sum()

(1, (6,), 6, dtype('float64'), 21.0)

In [5]:
a =a.astype(np.int32)#تغییر type
a

array([1, 2, 3, 4, 5, 6])

In [6]:
lst = [[1,2,3,4,5], [6,7,8,9,10]]
lst

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [11]:
b = np.array([[1,2,3,4,5], [6,7,8,9,10]], dtype=np.float64)
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [10]:
b = np.array(lst, dtype=np.float64)
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [14]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

In [15]:
b.dtype

dtype('float64')

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [22]:
np.random.standard_normal((2,3))

array([[-0.12260601, -0.15032126,  0.55115641],
       [-0.43341781, -0.28609327, -1.27238633]])

In [23]:
a= np.random.standard_normal((2,3))
b= np.random.standard_normal((2,3))

In [24]:
np.vstack([a,b])#

array([[ 0.26359283, -0.6143776 ,  0.15854978],
       [-0.38278783, -1.17325554,  0.34088336],
       [-0.3967682 ,  0.46523059,  1.37981094],
       [ 1.5011015 , -0.18054229,  0.01382525]])

In [27]:
c =np.random.standard_t(2)
c

-3.1952773512732886

In [28]:
np.hstack([a,b])

array([[ 0.26359283, -0.6143776 ,  0.15854978, -0.3967682 ,  0.46523059,
         1.37981094],
       [-0.38278783, -1.17325554,  0.34088336,  1.5011015 , -0.18054229,
         0.01382525]])

In [29]:
a. transpose()

array([[ 0.26359283, -0.38278783],
       [-0.6143776 , -1.17325554],
       [ 0.15854978,  0.34088336]])

In [30]:
a= np.array([1,2,3,4])
a.shape, a

((4,), array([1, 2, 3, 4]))

In [31]:
b = a.T#transpose
b.shape

(4,)

In [32]:
np.all(b == a)

True

In [33]:
b == a

array([ True,  True,  True,  True])

In [34]:
a = np.array([[1,2,3,4]])
a.shape, a

((1, 4), array([[1, 2, 3, 4]]))

In [35]:
b= a.T
b.shape

(4, 1)

In [36]:
np.all(a==b)

False

In [37]:
#ذخیره و لود نامپای روی هارد اگه دیتا ست سنگین بود
np.save('example.npy', a)

In [38]:
a1= np.load('example.npy')

In [39]:
v = np.linspace(0,10,5)
v + 1

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [41]:
ones = np.ones((6,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
twos = np.ones((6,1)) * 2
twos

array([[2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.]])

In [43]:
ones + twos

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [44]:
ones.shape

(6, 5)

In [45]:
twos.shape

(6, 1)

In [46]:
x = np.linspace(0,100,10000000)
x.shape

(10000000,)

In [47]:
x.size

10000000

In [48]:
import math 
def get_lst(x):
    lst = []
    for i in x:
        lst.append(math.sin(i))
    return lst

In [2]:
import numpy as np

In [3]:
v = np.linspace(0,10,5)
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [4]:
v[0]

0.0

In [5]:
v[3]

7.5

In [6]:
v[-1]

10.0

In [7]:
bool_index = v > 0
bool_index

array([False,  True,  True,  True,  True])

In [8]:
v[[0,3]] = [[4,5]]
v

array([ 4. ,  2.5,  5. ,  5. , 10. ])